labels:
  - love and relationships
  - career and ambitions
  - finance and wealth
  - health and wellness
  - personal growth
  - friendships and social life
  - spirituality and higher purpose
  - decisions and dilemmas
  - timing and future
  - creativity and expression